### ISSUE TITLE
Deployment requires annotation, not label, to trigger injection

### ISSUE THREAD

**Issue by alexnederlof** [1Password/kubernetes-secrets-injector#33]
### Your environment

Secret Injector Version: 1.0.1

1Password CLI Version:

## What happened?
Injector said the pod did not need injection, while it does:

```
 I0530 20:06:17.573064       1 webhook.go:98] Pod  at namespace optest. Secret injection status:  Secret Injection Enabled:false
```

While it had the following meta data:

```yml
metadata:
      labels:
        app.kubernetes.io/name: tester
        operator.1password.io/inject: "exporter"
```

But it seems from [the code](https://github.com/1Password/kubernetes-secrets-injector/blob/bf41987662ad868b2b06ed8f3d5e1c2ebe38140e/pkg/webhook/webhook.go#L89), that it does not check the label (as the docs claim but it checks the label. So if you change it to:

```yml
metadata:
      labels:
        app.kubernetes.io/name: tester
        operator.1password.io/inject: "exporter"
      annotations:
        operator.1password.io/inject: "exporter"
```

It does work.

So either the code or the docs need updating I guess?
